repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=crlf]
  - id: pretty-format-json
    args: [--autofix]
  - id: check-toml
- repo: https://github.com/dotnet/format
  rev: v8.0.453106
  hooks:
  - id: dotnet-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]
