[build]
icon = "./icons/feralcompany-static-icon.png"
outdir = "../dist"
readme = "../README.md"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../assets/locales"
target = "plugins/FeralCompany/locales"

[[build.copy]]
source = "../FeralCompany/bin/FeralCompany.dll"
target = "plugins/FeralCompany/"

[[build.copy]]
source = "../FeralCompany_Unity/AssetBundles/feralcompany_assets"
target = "plugins/FeralCompany/"

[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
containsNsfwContent = false
description = "Collection of game \"enhancements\" such as Minimap, Night Vision, etc."
name = "FeralCompany"
namespace = "Ferus"
websiteUrl = "https://github.com/FeralCompany/FeralCompany"

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Rune580-LethalCompany_InputUtils = "0.7.7"

[publish]
communities = ["lethal-company"]

# Goals:
# "bug-fixes", "translations", "tweaks-and-quality-of-life"
[publish.categories]
lethal-company = ["bepinex", "clientside", "misc", "mods"]
