name: Build Project
on:
  push:
    branches: ['**']
  pull_request:
jobs:
  build:
    uses: ./.github/workflows/build_common.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
